import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import Navbar from "@/components/common/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mohan - A Full Stack Web Developer",
  description: "Generated by create next app", // Add description
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.className} min-h-[200vh]  antialiased`}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionChange>
          <Navbar/>
          {children}
          </ThemeProvider>
          </body>
      </html>
    </ViewTransitions>
  );
}
